Metrics/ClassLength:
  Exclude:
    - 'lib/valkyrie/persistence/fedora/persister.rb'
    - 'lib/valkyrie/persistence/postgres/query_service.rb'
    - 'lib/valkyrie/resource.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/valkyrie/persistence/fedora/persister.rb'